// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: productVariant.sql

package db

import (
	"context"
	"database/sql"
)

const createProductVariant = `-- name: CreateProductVariant :one
INSERT INTO product_variant (
                               price, pd_id , att_id
) VALUES (
             $1 , $2 , $3
         )
RETURNING product_variant_id, created_at, updated_at, deleted_at, price, pd_id, att_id
`

type CreateProductVariantParams struct {
	Price string        `json:"price"`
	PdID  sql.NullInt64 `json:"pd_id"`
	AttID sql.NullInt64 `json:"att_id"`
}

func (q *Queries) CreateProductVariant(ctx context.Context, arg CreateProductVariantParams) (ProductVariant, error) {
	row := q.db.QueryRowContext(ctx, createProductVariant, arg.Price, arg.PdID, arg.AttID)
	var i ProductVariant
	err := row.Scan(
		&i.ProductVariantID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Price,
		&i.PdID,
		&i.AttID,
	)
	return i, err
}

const deleteProductVariant = `-- name: DeleteProductVariant :exec
DELETE FROM product_variant
WHERE product_variant_id = $1
`

func (q *Queries) DeleteProductVariant(ctx context.Context, productVariantID int64) error {
	_, err := q.db.ExecContext(ctx, deleteProductVariant, productVariantID)
	return err
}

const deleteProductVariantTemporarily = `-- name: DeleteProductVariantTemporarily :one
UPDATE product_variant
SET deleted_at = now()
WHERE product_variant_id = $1 AND deleted_at IS NULL
RETURNING  product_variant_id, created_at, updated_at, deleted_at, price, pd_id, att_id
`

func (q *Queries) DeleteProductVariantTemporarily(ctx context.Context, productVariantID int64) (ProductVariant, error) {
	row := q.db.QueryRowContext(ctx, deleteProductVariantTemporarily, productVariantID)
	var i ProductVariant
	err := row.Scan(
		&i.ProductVariantID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Price,
		&i.PdID,
		&i.AttID,
	)
	return i, err
}

const getProductVariant = `-- name: GetProductVariant :one
SELECT product_variant_id, created_at, updated_at, deleted_at, price, pd_id, att_id FROM product_variant
WHERE product_variant_id = $1
AND deleted_at IS NULL
`

func (q *Queries) GetProductVariant(ctx context.Context, productVariantID int64) (ProductVariant, error) {
	row := q.db.QueryRowContext(ctx, getProductVariant, productVariantID)
	var i ProductVariant
	err := row.Scan(
		&i.ProductVariantID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Price,
		&i.PdID,
		&i.AttID,
	)
	return i, err
}

const listProductsVariant = `-- name: ListProductsVariant :many
SELECT product_variant_id, created_at, updated_at, deleted_at, price, pd_id, att_id FROM product_variant
WHERE deleted_at IS NULL
ORDER BY pd_id
LIMIT $1
OFFSET $2
`

type ListProductsVariantParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListProductsVariant(ctx context.Context, arg ListProductsVariantParams) ([]ProductVariant, error) {
	rows, err := q.db.QueryContext(ctx, listProductsVariant, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductVariant
	for rows.Next() {
		var i ProductVariant
		if err := rows.Scan(
			&i.ProductVariantID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Price,
			&i.PdID,
			&i.AttID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreProductVariant = `-- name: RestoreProductVariant :one
UPDATE product_variant
SET deleted_at = NULL
WHERE product_variant_id = $1 AND deleted_at IS NOT NULL
RETURNING  product_variant_id, created_at, updated_at, deleted_at, price, pd_id, att_id
`

func (q *Queries) RestoreProductVariant(ctx context.Context, productVariantID int64) (ProductVariant, error) {
	row := q.db.QueryRowContext(ctx, restoreProductVariant, productVariantID)
	var i ProductVariant
	err := row.Scan(
		&i.ProductVariantID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Price,
		&i.PdID,
		&i.AttID,
	)
	return i, err
}

const updateProductVariant = `-- name: UpdateProductVariant :one
UPDATE product_variant
SET price = $1,
    pd_id = $2,
    att_id = $3,
    updated_at = now()
WHERE product_variant_id = $4 AND deleted_at IS NULL
RETURNING  product_variant_id, created_at, updated_at, deleted_at, price, pd_id, att_id
`

type UpdateProductVariantParams struct {
	Price            string        `json:"price"`
	PdID             sql.NullInt64 `json:"pd_id"`
	AttID            sql.NullInt64 `json:"att_id"`
	ProductVariantID int64         `json:"product_variant_id"`
}

func (q *Queries) UpdateProductVariant(ctx context.Context, arg UpdateProductVariantParams) (ProductVariant, error) {
	row := q.db.QueryRowContext(ctx, updateProductVariant,
		arg.Price,
		arg.PdID,
		arg.AttID,
		arg.ProductVariantID,
	)
	var i ProductVariant
	err := row.Scan(
		&i.ProductVariantID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Price,
		&i.PdID,
		&i.AttID,
	)
	return i, err
}
